name: final-project-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.10.2
      - scikit-learn==1.4.0
      - pandas==2.1.4
      - numpy==1.26.3
      - matplotlib==3.8.2
      - gradio==4.20.0
      - openai  
